version: '2.1'

services:
  # Apache2 server node.
  web:
    env_file: .env
    hostname: web
    image: docksal/web:edge-apache2.2
  # image: docksal/web:edge-apache2.4
    ports:
      # Port forwarding will use your port in Windows. So be sure that you have nothing on 80 and 443 port.
      # Usually these ports used by skype and `server` service in Windows.
      - 80:80
      - 443:443
    links:
      - cli
    volumes_from:
      - cli
    extra_hosts:
      - "host:${HOST_IP}"

  # CLI node.
  # Used for PHP-FPM, all console commands and tools.
  cli:
    env_file: .env
    hostname: cli
    image: docksal/cli:1.0-php5
  # image: docksal/cli:1.0-php7
  # image: docksal/cli:edge-php7 # PHP 7.0.15
    ports:
      - "2221:22" # SSH Port
    volumes:
      - "./:/var/www"                                           # Map current directory to /var/www
      - ".docksal/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"  # MySQL configuration overrides
      - ".docksal/etc/php/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
      - ".docksal/etc/php/php-cli.ini:/etc/php5/cli/conf.d/z_php.ini"
      - "~/.ssh:/home/docker/.ssh"                              # SSH keys mapping to container's ~/.ssh.
    extra_hosts:
      # Additional hosts that appears on /etc/hosts of container.
      - "host:${HOST_IP}"

  # Database (MySQL)
  db:
    env_file: .env
    hostname: db
    image: docksal/db:1.0-mysql-5.5
  # image: docksal/db:1.0-mysql-5.6
  # image: docksal/db:1.0-mysql-5.7
  # image: docksal/db:1.0-mysql-8.0
  # image: percona:5.5
  # image: percona:5.6
  # image: percona:5.7
    ports:
      - "3306:3306"
    links:
      - cli
    volumes_from:
      - cli
    extra_hosts:
      - "host:${HOST_IP}"

  # # Selenium2 node.
  # browser:
  #   env_file: .env
  #   hostname: browser
  #   image: selenium/standalone-chrome-debug:latest
  # # image: selenium/standalone-firefox-debug:latest
  #   ports:
  #     - 4444:4444
  #     - 5900:5900 # Use 'secret' as a password for connectin via VNC to this port.
  #   extra_hosts:
  #     - "host:${HOST_IP}"
  #   links:
  #     - cli
  #   volumes_from:
  #     - cli

  # # Solr
  # solr:
  #   env_file: .env
  #   hostname: solr
  # # image: docksal/solr:1.0-solr3
  #   image: docksal/solr:1.0-solr4
  #   links:
  #     - cli
  #   volumes_from:
  #     - cli
  #   extra_hosts:
  #     - "host:${HOST_IP}"

  # # Memcached node.
  # memcached:
  #   env_file: .env
  #   hostname: memcached
  #   image: memcached
  #   extra_hosts:
  #     - "host:${HOST_IP}"
  #   ports:
  #     - 11211
  #   links:
  #     - cli
