version: '2'
services:
  # Apache2 server node.
  web:
    env_file: .env
    hostname: web
    image: docksal/apache:2.2-stable
    #image: docksal/apache:2.4-stable
    ports:
      # Port forwarding will use your port in Windows. So be sure that you have nothing on 80 and 443 port.
      # Usually these ports used by skype and `server` service in Windows.
      - 80:80
      - 443:443
    links:
      - cli
    volumes_from:
      - cli

  # CLI node.
  # Used for PHP-FPM, all console commands and tools.
  cli:
    env_file: .env
    hostname: cli
    image: docksal/cli:edge      # PHP 5.6.29
   #image: docksal/cli:edge-php7 # PHP 7.0.15
    ports:
      - "2221:22" # SSH Port
    volumes:
      - "./:/var/www"                                                    # Map current directory to /var/www
      - ".drude/etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"         # PHP5 FPM configuration overrides
      - ".drude/etc/php5/php-cli.ini:/etc/php5/cli/conf.d/z_php.ini"     # PHP5 CLI configuration overrides
      #- ".drude/etc/php5/php.ini:/etc/php/7.0/fpm/conf.d/z_php.ini"     # PHP7 FPM configuration overrides
      #- ".drude/etc/php5/php-cli.ini:/etc/php/7.0/cli/conf.d/z_php.ini" # PHP7 CLI configuration overrides
      - ".drude/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"             # MySQL configuration overrides
      - "~/.ssh:/home/docker/.ssh"                                       # SSH keys mapping to containers ~/.ssh.
    extra_hosts:
      # Additional hosts that appears on /etc/hosts of container.
      - "host:${HOST_IP}"

  # MySQL database node.
  db:
    env_file: .env
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    #image: docksal/db:1.0-mysql-5.6
    #image: docksal/db:1.0-mysql-5.7
    #image: docksal/db:1.0-mysql-8.0
    #image: percona:5.5
    #image: percona:5.6
    #image: percona:5.7
    #image: mariadb:5.5
    ports:
      # Port forwarding will use your port in Windows. So be sure that you have no MySQL running in Windows.
      - 3306:3306
    environment:
      # MySQL credentials.
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
    extra_hosts:
      - "host:${HOST_IP}"
    links:
      - cli
    volumes_from:
      - cli

  # Selenium2 node.
  browser:
    env_file: .env
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900 # Use 'secret' as a password for connectin via VNC to this port.
    extra_hosts:
      - "host:${HOST_IP}"
    links:
      - cli
    volumes_from:
      - cli

  # Solr node.
  solr:
    env_file: .env
    hostname: solr
    image: docksal/solr:3.x-stable
    ports:
      - 8983:8983
    extra_hosts:
      - "host:${HOST_IP}"
    links:
      - cli

  # Memcached node.
  memcached:
    env_file: .env
    hostname: memcached
    image: memcached
    environment:
      - MEMCACHED_MEMORY_LIMIT=128 # Memcached memory limit in megabytes
    extra_hosts:
      - "host:${HOST_IP}"
    ports:
      - 11211:11211
    links:
      - cli
